// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvdnenltwifmnsaytnyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZG5lbmx0d2lmbW5zYXl0bnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjY4ODMsImV4cCI6MjA3MjY0Mjg4M30.05nuCTfOK_0ic8TuPZ-7RopgzYOG_YFDYIW3tkGXlXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});